
import javax.swing.JDialog;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mARC
 */
public class pizzaConversion2 extends javax.swing.JFrame {

    /**
     * Creates new form pizzaConversion
     */
    public pizzaConversion2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogDeluxe = new javax.swing.JDialog();
        dPanel = new javax.swing.JPanel();
        deluxePanel2 = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        deluxePanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        qty5 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        total5 = new javax.swing.JTextField();
        buy5 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        dialogSpecial = new javax.swing.JDialog();
        sPanel = new javax.swing.JPanel();
        specialPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        qty2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        total2 = new javax.swing.JTextField();
        buy2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        specialPanel2 = new javax.swing.JPanel();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        dialogPromo = new javax.swing.JDialog();
        pPanel = new javax.swing.JPanel();
        promoPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        qty3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        total3 = new javax.swing.JTextField();
        buy3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        promoPanel2 = new javax.swing.JPanel();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        deluxePanel1 = new javax.swing.JPanel();
        deluxeButt = new javax.swing.JButton();
        specialPanel = new javax.swing.JPanel();
        specialButt = new javax.swing.JButton();
        promoPanel = new javax.swing.JPanel();
        promoButt = new javax.swing.JButton();

        deluxePanel2.setBackground(new java.awt.Color(0, 204, 204));

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox6.setText("Cheese");

        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox7.setText("Bacon");

        jCheckBox8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox8.setText("Ham");

        jCheckBox9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox9.setText("Onions");

        jCheckBox10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox10.setText("Chili");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ingredients:");

        javax.swing.GroupLayout deluxePanel2Layout = new javax.swing.GroupLayout(deluxePanel2);
        deluxePanel2.setLayout(deluxePanel2Layout);
        deluxePanel2Layout.setHorizontalGroup(
            deluxePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deluxePanel2Layout.createSequentialGroup()
                .addGroup(deluxePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deluxePanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(deluxePanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(deluxePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox10)
                            .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        deluxePanel2Layout.setVerticalGroup(
            deluxePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deluxePanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox10)
                .addGap(68, 68, 68))
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("PRICE: ₱185");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("QUANTITY");

        qty5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("TOTAL:");

        total5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        buy5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buy5.setText("BUY");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel23.setText("DELUXE PIZZA");

        javax.swing.GroupLayout deluxePanel5Layout = new javax.swing.GroupLayout(deluxePanel5);
        deluxePanel5.setLayout(deluxePanel5Layout);
        deluxePanel5Layout.setHorizontalGroup(
            deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deluxePanel5Layout.createSequentialGroup()
                .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deluxePanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20))
                    .addGroup(deluxePanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(qty5, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(total5)))
                    .addGroup(deluxePanel5Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(buy5))
                    .addGroup(deluxePanel5Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel23)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        deluxePanel5Layout.setVerticalGroup(
            deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deluxePanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(13, 13, 13)
                .addComponent(jLabel23)
                .addGap(29, 29, 29)
                .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(deluxePanel5Layout.createSequentialGroup()
                        .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(qty5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(total5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(buy5)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout dPanelLayout = new javax.swing.GroupLayout(dPanel);
        dPanel.setLayout(dPanelLayout);
        dPanelLayout.setHorizontalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dPanelLayout.createSequentialGroup()
                .addComponent(deluxePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deluxePanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dPanelLayout.setVerticalGroup(
            dPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deluxePanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deluxePanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dialogDeluxeLayout = new javax.swing.GroupLayout(dialogDeluxe.getContentPane());
        dialogDeluxe.getContentPane().setLayout(dialogDeluxeLayout);
        dialogDeluxeLayout.setHorizontalGroup(
            dialogDeluxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogDeluxeLayout.setVerticalGroup(
            dialogDeluxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("PRICE: ₱250");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("QUANTITY");

        qty2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("TOTAL:");

        total2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        buy2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buy2.setText("BUY");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("SPECIAL PIZZA");

        javax.swing.GroupLayout specialPanel3Layout = new javax.swing.GroupLayout(specialPanel3);
        specialPanel3.setLayout(specialPanel3Layout);
        specialPanel3Layout.setHorizontalGroup(
            specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialPanel3Layout.createSequentialGroup()
                .addGroup(specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(specialPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(specialPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qty2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(specialPanel3Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(buy2))
                    .addGroup(specialPanel3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel5)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        specialPanel3Layout.setVerticalGroup(
            specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qty2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(45, 45, 45)
                .addComponent(buy2)
                .addGap(57, 57, 57))
        );

        specialPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jCheckBox17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox17.setText("Cheese");

        jCheckBox18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox18.setText("Pepper");

        jCheckBox19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox19.setText("Bacon");

        jCheckBox20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox20.setText("Ham");

        jCheckBox21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox21.setText("Onions");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Ingredients:");

        jCheckBox22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox22.setText("Chili");

        jCheckBox23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox23.setText("Mushroom");
        jCheckBox23.setActionCommand("Mushroom");

        javax.swing.GroupLayout specialPanel2Layout = new javax.swing.GroupLayout(specialPanel2);
        specialPanel2.setLayout(specialPanel2Layout);
        specialPanel2Layout.setHorizontalGroup(
            specialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialPanel2Layout.createSequentialGroup()
                .addGroup(specialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(specialPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(specialPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(specialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox21)
                            .addComponent(jCheckBox17, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox19, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox20, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox22)
                            .addComponent(jCheckBox23))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        specialPanel2Layout.setVerticalGroup(
            specialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox22)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout sPanelLayout = new javax.swing.GroupLayout(sPanel);
        sPanel.setLayout(sPanelLayout);
        sPanelLayout.setHorizontalGroup(
            sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(specialPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        sPanelLayout.setVerticalGroup(
            sPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(specialPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sPanelLayout.createSequentialGroup()
                .addComponent(specialPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogSpecialLayout = new javax.swing.GroupLayout(dialogSpecial.getContentPane());
        dialogSpecial.getContentPane().setLayout(dialogSpecialLayout);
        dialogSpecialLayout.setHorizontalGroup(
            dialogSpecialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogSpecialLayout.setVerticalGroup(
            dialogSpecialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("PRICE: ₱290");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("QUANTITY");

        qty3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("TOTAL:");

        total3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        buy3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buy3.setText("BUY");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setText("PROMO PIZZA");
        jLabel14.setToolTipText("");

        javax.swing.GroupLayout promoPanel3Layout = new javax.swing.GroupLayout(promoPanel3);
        promoPanel3.setLayout(promoPanel3Layout);
        promoPanel3Layout.setHorizontalGroup(
            promoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoPanel3Layout.createSequentialGroup()
                .addGroup(promoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(promoPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(promoPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(promoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(promoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qty3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(promoPanel3Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(buy3))
                    .addGroup(promoPanel3Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel14)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        promoPanel3Layout.setVerticalGroup(
            promoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(promoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qty3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(promoPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(45, 45, 45)
                .addComponent(buy3)
                .addGap(57, 57, 57))
        );

        promoPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jCheckBox24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox24.setText("Cheese");

        jCheckBox25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox25.setText("Pepper");

        jCheckBox26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox26.setText("Bacon");

        jCheckBox27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox27.setText("Ham");

        jCheckBox28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox28.setText("Onions");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Ingredients:");

        jCheckBox29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox29.setText("Chili");

        jCheckBox30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox30.setText("Mushroom");

        javax.swing.GroupLayout promoPanel2Layout = new javax.swing.GroupLayout(promoPanel2);
        promoPanel2.setLayout(promoPanel2Layout);
        promoPanel2Layout.setHorizontalGroup(
            promoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoPanel2Layout.createSequentialGroup()
                .addGroup(promoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(promoPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(promoPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(promoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox28)
                            .addComponent(jCheckBox24, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox25, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox26, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox27, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox29)
                            .addComponent(jCheckBox30))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        promoPanel2Layout.setVerticalGroup(
            promoPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox29)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout pPanelLayout = new javax.swing.GroupLayout(pPanel);
        pPanel.setLayout(pPanelLayout);
        pPanelLayout.setHorizontalGroup(
            pPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(promoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promoPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pPanelLayout.setVerticalGroup(
            pPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(promoPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pPanelLayout.createSequentialGroup()
                .addComponent(promoPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogPromoLayout = new javax.swing.GroupLayout(dialogPromo.getContentPane());
        dialogPromo.getContentPane().setLayout(dialogPromoLayout);
        dialogPromoLayout.setHorizontalGroup(
            dialogPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogPromoLayout.setVerticalGroup(
            dialogPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        deluxePanel1.setBackground(new java.awt.Color(0, 204, 51));

        deluxeButt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deluxeButt.setText("DELUXE PIZZA");
        deluxeButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deluxeButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deluxePanel1Layout = new javax.swing.GroupLayout(deluxePanel1);
        deluxePanel1.setLayout(deluxePanel1Layout);
        deluxePanel1Layout.setHorizontalGroup(
            deluxePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deluxePanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(deluxeButt)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        deluxePanel1Layout.setVerticalGroup(
            deluxePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deluxePanel1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(deluxeButt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        specialPanel.setBackground(new java.awt.Color(204, 0, 0));

        specialButt.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        specialButt.setText("SPECIAL PIZZA");

        javax.swing.GroupLayout specialPanelLayout = new javax.swing.GroupLayout(specialPanel);
        specialPanel.setLayout(specialPanelLayout);
        specialPanelLayout.setHorizontalGroup(
            specialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(specialButt)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        specialPanelLayout.setVerticalGroup(
            specialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(specialButt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        promoPanel.setBackground(new java.awt.Color(0, 51, 153));

        promoButt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        promoButt.setText("PROMO PIZZA");

        javax.swing.GroupLayout promoPanelLayout = new javax.swing.GroupLayout(promoPanel);
        promoPanel.setLayout(promoPanelLayout);
        promoPanelLayout.setHorizontalGroup(
            promoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, promoPanelLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(promoButt)
                .addGap(59, 59, 59))
        );
        promoPanelLayout.setVerticalGroup(
            promoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoPanelLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(promoButt)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(deluxePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deluxePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(specialPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(promoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deluxeButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deluxeButtActionPerformed
        dialogDeluxe.getContentPane().add(dPanel);
    
        dialogDeluxe.setVisible(true);
    }//GEN-LAST:event_deluxeButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pizzaConversion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pizzaConversion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pizzaConversion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pizzaConversion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pizzaConversion2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buy1;
    private javax.swing.JButton buy2;
    private javax.swing.JButton buy3;
    private javax.swing.JButton buy4;
    private javax.swing.JButton buy5;
    private javax.swing.JPanel dPanel;
    private javax.swing.JButton deluxeButt;
    private javax.swing.JPanel deluxePanel1;
    private javax.swing.JPanel deluxePanel2;
    private javax.swing.JPanel deluxePanel3;
    private javax.swing.JPanel deluxePanel4;
    private javax.swing.JPanel deluxePanel5;
    private javax.swing.JDialog dialogDeluxe;
    private javax.swing.JDialog dialogPromo;
    private javax.swing.JDialog dialogSpecial;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pPanel;
    private javax.swing.JButton promoButt;
    private javax.swing.JPanel promoPanel;
    private javax.swing.JPanel promoPanel2;
    private javax.swing.JPanel promoPanel3;
    private javax.swing.JTextField qty1;
    private javax.swing.JTextField qty2;
    private javax.swing.JTextField qty3;
    private javax.swing.JTextField qty4;
    private javax.swing.JTextField qty5;
    private javax.swing.JPanel sPanel;
    private javax.swing.JButton specialButt;
    private javax.swing.JPanel specialPanel;
    private javax.swing.JPanel specialPanel2;
    private javax.swing.JPanel specialPanel3;
    private javax.swing.JTextField total1;
    private javax.swing.JTextField total2;
    private javax.swing.JTextField total3;
    private javax.swing.JTextField total4;
    private javax.swing.JTextField total5;
    // End of variables declaration//GEN-END:variables
}
