
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mARC
 */
public class pizzaConversion extends javax.swing.JFrame {
    
    /**
     * Creates new form pizzaConversion2
     */
    public pizzaConversion() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        deluxePanel2 = new javax.swing.JPanel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        deluxePanel5 = new javax.swing.JPanel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        qty31 = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        total31 = new javax.swing.JTextField();
        buy31 = new javax.swing.JButton();
        jLabel130 = new javax.swing.JLabel();
        homeButt1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        specialPanel2 = new javax.swing.JPanel();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        specialPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        qty2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        total2 = new javax.swing.JTextField();
        buy2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        homeButt2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        promoPanel33 = new javax.swing.JPanel();
        jCheckBox45 = new javax.swing.JCheckBox();
        jCheckBox46 = new javax.swing.JCheckBox();
        jCheckBox47 = new javax.swing.JCheckBox();
        jCheckBox48 = new javax.swing.JCheckBox();
        jCheckBox49 = new javax.swing.JCheckBox();
        jLabel126 = new javax.swing.JLabel();
        jCheckBox50 = new javax.swing.JCheckBox();
        jCheckBox51 = new javax.swing.JCheckBox();
        promoPanel32 = new javax.swing.JPanel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        qty30 = new javax.swing.JTextField();
        jLabel124 = new javax.swing.JLabel();
        total30 = new javax.swing.JTextField();
        buy30 = new javax.swing.JButton();
        jLabel125 = new javax.swing.JLabel();
        homeButt3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("DELUXE PIZZA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(40, 200, 120, 23);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("SPECIAL PIZZA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(230, 200, 120, 23);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("PROMO PIZZA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(420, 200, 120, 23);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton4.setText("PIZZA SHOP");
        jPanel4.add(jButton4);
        jButton4.setBounds(190, 40, 190, 39);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mARC\\OneDrive\\Documents\\NetBeansProjects\\pizzaConversion\\src\\deluxe-pizza-presnetation.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(-10, -50, 600, 800);

        tabbedPane.addTab("HOME", jPanel4);

        deluxePanel2.setBackground(new java.awt.Color(0, 204, 204));

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox6.setText("Cheese");

        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox7.setText("Bacon");

        jCheckBox8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox8.setText("Ham");

        jCheckBox9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox9.setText("Onions");

        jCheckBox10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox10.setText("Chili");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ingredients:");

        javax.swing.GroupLayout deluxePanel2Layout = new javax.swing.GroupLayout(deluxePanel2);
        deluxePanel2.setLayout(deluxePanel2Layout);
        deluxePanel2Layout.setHorizontalGroup(
            deluxePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deluxePanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(deluxePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(deluxePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox10)
                        .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        deluxePanel2Layout.setVerticalGroup(
            deluxePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deluxePanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox10)
                .addGap(111, 111, 111))
        );

        jLabel127.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel127.setText("PRICE: ₱185");

        jLabel128.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel128.setText("QUANTITY");

        qty31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qty31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty31ActionPerformed(evt);
            }
        });

        jLabel129.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel129.setText("TOTAL:");

        total31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        total31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total31ActionPerformed(evt);
            }
        });

        buy31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buy31.setText("BUY");
        buy31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy31ActionPerformed(evt);
            }
        });

        jLabel130.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel130.setText("DELUXE PIZZA");

        homeButt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homeButt1.setText("HOME");
        homeButt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deluxePanel5Layout = new javax.swing.GroupLayout(deluxePanel5);
        deluxePanel5.setLayout(deluxePanel5Layout);
        deluxePanel5Layout.setHorizontalGroup(
            deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deluxePanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel127)
                .addGap(19, 19, 19))
            .addGroup(deluxePanel5Layout.createSequentialGroup()
                .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deluxePanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel128)
                            .addComponent(jLabel129))
                        .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deluxePanel5Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(buy31))
                            .addGroup(deluxePanel5Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(total31, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                    .addComponent(qty31)))))
                    .addGroup(deluxePanel5Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel130)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        deluxePanel5Layout.setVerticalGroup(
            deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deluxePanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel127)
                    .addComponent(homeButt1))
                .addGap(44, 44, 44)
                .addComponent(jLabel130)
                .addGap(31, 31, 31)
                .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel128)
                    .addComponent(qty31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(deluxePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel129))
                .addGap(36, 36, 36)
                .addComponent(buy31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(deluxePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deluxePanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deluxePanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deluxePanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPane.addTab("DELUXE", jPanel1);

        specialPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jCheckBox17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox17.setText("Cheese");

        jCheckBox18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox18.setText("Pepper");

        jCheckBox19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox19.setText("Bacon");

        jCheckBox20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox20.setText("Ham");

        jCheckBox21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox21.setText("Onions");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Ingredients:");

        jCheckBox22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox22.setText("Chili");

        jCheckBox23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox23.setText("Mushroom");

        javax.swing.GroupLayout specialPanel2Layout = new javax.swing.GroupLayout(specialPanel2);
        specialPanel2.setLayout(specialPanel2Layout);
        specialPanel2Layout.setHorizontalGroup(
            specialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(specialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, specialPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(specialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox23)
                            .addGroup(specialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCheckBox18, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox17, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox19, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox20, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox21)
                            .addComponent(jCheckBox22)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        specialPanel2Layout.setVerticalGroup(
            specialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox22)
                .addGap(76, 76, 76))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("PRICE: ₱250");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("QUANTITY");

        qty2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("TOTAL:");

        total2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        total2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total2ActionPerformed(evt);
            }
        });

        buy2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buy2.setText("BUY");
        buy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("SPECIAL PIZZA");

        homeButt2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homeButt2.setText("HOME");
        homeButt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout specialPanel3Layout = new javax.swing.GroupLayout(specialPanel3);
        specialPanel3.setLayout(specialPanel3Layout);
        specialPanel3Layout.setHorizontalGroup(
            specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addGroup(specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qty2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(specialPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(buy2)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(specialPanel3Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );
        specialPanel3Layout.setVerticalGroup(
            specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(homeButt2))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(54, 54, 54)
                .addGroup(specialPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(40, 40, 40)
                .addComponent(buy2)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(specialPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(specialPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(specialPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPane.addTab("SPECIAL", jPanel2);

        promoPanel33.setBackground(new java.awt.Color(0, 204, 204));

        jCheckBox45.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox45.setText("Cheese");

        jCheckBox46.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox46.setText("Pepper");

        jCheckBox47.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox47.setText("Bacon");

        jCheckBox48.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox48.setText("Ham");

        jCheckBox49.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox49.setText("Onions");

        jLabel126.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel126.setText("Ingredients:");

        jCheckBox50.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox50.setText("Chili");

        jCheckBox51.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox51.setText("Mushroom");

        javax.swing.GroupLayout promoPanel33Layout = new javax.swing.GroupLayout(promoPanel33);
        promoPanel33.setLayout(promoPanel33Layout);
        promoPanel33Layout.setHorizontalGroup(
            promoPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoPanel33Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(promoPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(promoPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox49)
                        .addComponent(jCheckBox45, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox46, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox47, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox48, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckBox50)
                        .addComponent(jCheckBox51))
                    .addGroup(promoPanel33Layout.createSequentialGroup()
                        .addComponent(jLabel126)
                        .addGap(31, 31, 31)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        promoPanel33Layout.setVerticalGroup(
            promoPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoPanel33Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel126)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox50)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jLabel122.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel122.setText("PRICE: ₱290");

        jLabel123.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel123.setText("QUANTITY");

        qty30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qty30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty30ActionPerformed(evt);
            }
        });

        jLabel124.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel124.setText("TOTAL:");

        total30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        total30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total30ActionPerformed(evt);
            }
        });

        buy30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buy30.setText("BUY");
        buy30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy30ActionPerformed(evt);
            }
        });

        jLabel125.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel125.setText("PROMO PIZZA");
        jLabel125.setToolTipText("");

        homeButt3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homeButt3.setText("HOME");
        homeButt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButt3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout promoPanel32Layout = new javax.swing.GroupLayout(promoPanel32);
        promoPanel32.setLayout(promoPanel32Layout);
        promoPanel32Layout.setHorizontalGroup(
            promoPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoPanel32Layout.createSequentialGroup()
                .addGroup(promoPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(promoPanel32Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel125))
                    .addGroup(promoPanel32Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(buy30))
                    .addGroup(promoPanel32Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(promoPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(promoPanel32Layout.createSequentialGroup()
                                .addComponent(homeButt3)
                                .addGap(194, 194, 194)
                                .addComponent(jLabel122))
                            .addGroup(promoPanel32Layout.createSequentialGroup()
                                .addGroup(promoPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel123)
                                    .addComponent(jLabel124))
                                .addGap(32, 32, 32)
                                .addGroup(promoPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qty30, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total30, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        promoPanel32Layout.setVerticalGroup(
            promoPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(promoPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(promoPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel122)
                    .addComponent(homeButt3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel125)
                .addGap(34, 34, 34)
                .addGroup(promoPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qty30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel123))
                .addGap(54, 54, 54)
                .addGroup(promoPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel124))
                .addGap(41, 41, 41)
                .addComponent(buy30)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(promoPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(promoPanel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(promoPanel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(promoPanel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabbedPane.addTab("PROMO", jPanel3);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -34, 580, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButt3ActionPerformed
        tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_homeButt3ActionPerformed

    private void total30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total30ActionPerformed

    private void qty30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty30ActionPerformed
        int a, b;

        a = Integer.parseInt(qty30.getText());

        if (a == 2){
            b = (a*290)-200; // Apply the discount to the total cost
            total30.setText(""+b);
        } else {
            b = a * 290; // No discount, regular price
            total30.setText(""+b);
        }
    }//GEN-LAST:event_qty30ActionPerformed

    private void homeButt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButt2ActionPerformed
        tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_homeButt2ActionPerformed

    private void total2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total2ActionPerformed

    private void qty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty2ActionPerformed
        int a, b;

        a = Integer.parseInt(qty2.getText());
        b = a * 250;

        total2.setText(""+b);
    }//GEN-LAST:event_qty2ActionPerformed

    private void homeButt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButt1ActionPerformed
        tabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_homeButt1ActionPerformed

    private void total31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total31ActionPerformed

    }//GEN-LAST:event_total31ActionPerformed

    private void qty31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty31ActionPerformed
        int a, b;

        a = Integer.parseInt(qty31.getText());
        b = a * 185;

        total31.setText(""+b);
    }//GEN-LAST:event_qty31ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buy31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy31ActionPerformed
        boolean txtChanged = false;
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you'll buy? You won't be able to redo your order.", "Caution", JOptionPane.YES_NO_CANCEL_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Thank you for purchasing!");
            // Set txtChanged to true if the user confirms the purchase
            txtChanged = true;
        } else if (confirm == JOptionPane.NO_OPTION) {
            // Set txtChanged to false if the user cancels the purchase
            txtChanged = false;
        }
    }//GEN-LAST:event_buy31ActionPerformed

    private void buy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy2ActionPerformed
        boolean txtChanged = false;
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you'll buy? You won't be able to redo your order.", "Caution", JOptionPane.YES_NO_CANCEL_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Thank you for purchasing!");
            // Set txtChanged to true if the user confirms the purchase
            txtChanged = true;
        } else if (confirm == JOptionPane.NO_OPTION) {
            // Set txtChanged to false if the user cancels the purchase
            txtChanged = false;
        }
    }//GEN-LAST:event_buy2ActionPerformed

    private void buy30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy30ActionPerformed
         boolean txtChanged = false;
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you'll buy? You won't be able to redo your order.", "Caution", JOptionPane.YES_NO_CANCEL_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Thank you for purchasing!");
            // Set txtChanged to true if the user confirms the purchase
            txtChanged = true;
        } else if (confirm == JOptionPane.NO_OPTION) {
            // Set txtChanged to false if the user cancels the purchase
            txtChanged = false;
}
    }//GEN-LAST:event_buy30ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pizzaConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pizzaConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pizzaConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pizzaConversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pizzaConversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buy2;
    private javax.swing.JButton buy30;
    private javax.swing.JButton buy31;
    private javax.swing.JPanel deluxePanel2;
    private javax.swing.JPanel deluxePanel5;
    private javax.swing.JButton homeButt1;
    private javax.swing.JButton homeButt2;
    private javax.swing.JButton homeButt3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox46;
    private javax.swing.JCheckBox jCheckBox47;
    private javax.swing.JCheckBox jCheckBox48;
    private javax.swing.JCheckBox jCheckBox49;
    private javax.swing.JCheckBox jCheckBox50;
    private javax.swing.JCheckBox jCheckBox51;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel promoPanel32;
    private javax.swing.JPanel promoPanel33;
    private javax.swing.JTextField qty2;
    private javax.swing.JTextField qty30;
    private javax.swing.JTextField qty31;
    private javax.swing.JPanel specialPanel2;
    private javax.swing.JPanel specialPanel3;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField total2;
    private javax.swing.JTextField total30;
    private javax.swing.JTextField total31;
    // End of variables declaration//GEN-END:variables
}
